#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running Husky...'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type Check'
    false;
)

# If everything passes... Now we can commit
echo 'Building...'

npm run build ||
(
    echo 'Typescript failed to build.'
    false;
)

# If everything passes... Now we can commit
echo 'Committing...'